service: grafico-eps-tri

provider:
  name: aws
  runtime: nodejs14.x
  stage: eps
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'